import { db, companyTable, servicesTable, projectsTable, caseStudiesTable } from "@workspace/db";
import { eq } from "drizzle-orm";

async function update() {
  console.log("Updating company data...");

  await db.update(companyTable).set({
    name: "Bridge Digital Solutions",
    tagline: "Engineering clarity. Delivering scale.",
    description: "Bridge Digital Solutions is a full-service digital agency specialising in custom software development, system architecture design, social media management, and multimedia production. We help businesses build robust digital infrastructure and commanding online presence.",
    email: "bridgedigitalsoulution9@gmail.com",
    phone: "+251955329318 | +251953395975",
    address: "220 East 42nd Street, Suite 600",
    city: "Addis Ababa",
    country: "Ethiopia",
    foundedYear: 2017,
    teamSize: "10–20",
    linkedinUrl: "https://linkedin.com/company/nexusdigitalsolutions",
    twitterUrl: "https://twitter.com/nexusdigitalhq",
    instagramUrl: "https://instagram.com/nexusdigitalhq",
    missionStatement: "To build digital systems that are fast, scalable, and designed to last — while creating a digital presence that commands attention and drives growth.",
    visionStatement: "A world where every ambitious business has access to enterprise-grade software and digital strategy, regardless of their size.",
  }).where(eq(companyTable.id, 1));
  console.log("Company updated");

  // Two comprehensive service categories
  await db.delete(servicesTable);
  await db.insert(servicesTable).values([
    {
      title: "Software Development",
      slug: "software-development",
      description: "End-to-end custom software engineering — from UI/UX design to deployment and ongoing maintenance. We build systems that scale.",
      content: "We design, build and ship production-ready software across every platform. Whether you need a consumer-facing web app, a cross-platform mobile application, an internal business tool or a complex API platform, our engineers own the full delivery lifecycle. We write clean, maintainable code backed by rigorous testing and CI/CD from day one.",
      iconName: "Code2",
      features: JSON.stringify([
        "UI/UX Design",
        "Custom Software Development",
        "Web Application Development",
        "Mobile Application Development",
        "Desktop Application Development",
        "Secure and Reliable Systems",
        "Database Design and Management",
        "API Integration",
        "Testing and Quality Assurance",
        "Deployment and Maintenance",
        "End-to-End Project Delivery",
      ]),
      coverImageUrl: "/images/proj-sw-1.png",
      sortOrder: 1,
      active: true,
    },
    {
      title: "Promotion & Media",
      slug: "promotion-media",
      description: "Professional multimedia production and strategic marketing campaigns that build your brand and grow your audience.",
      content: "From brand films to social media content engines, we produce high-quality multimedia assets and run the campaigns that put them in front of the right audience. Our production team handles everything from concept and scripting to filming, editing, and publishing — so your brand shows up consistently and compellingly across every channel.",
      iconName: "Film",
      features: JSON.stringify([
        "Professional Videography and Photography",
        "Video Editing and Production",
        "Social Media Content Creation",
        "Marketing Campaign Management",
        "Brand Promotion",
        "Content Planning and Publishing",
        "Creative Media Solutions",
      ]),
      coverImageUrl: "/images/proj-md-1.png",
      sortOrder: 2,
      active: true,
    },
  ]);
  console.log("Services updated");

  // 5 software + 4 promotion projects
  await db.delete(projectsTable);
  await db.insert(projectsTable).values([
    // SOFTWARE PROJECTS
    {
      title: "PriceFlow — SaaS Pricing Platform",
      slug: "priceflow-saas-platform",
      description: "Full redesign and rebuild of an internal price management system — microservices architecture, sub-200ms load times.",
      content: "PriceFlow's legacy Rails monolith had hit its ceiling. We designed a domain-driven microservices architecture on AWS, rebuilt the frontend in React with a modern dark-theme dashboard, and migrated 3 years of production data with zero downtime. The platform now handles 50,000 active users with 10x headroom for growth.\n\nDeployments shortened from 45 minutes to under 4. Engineers ship multiple times per day.",
      client: "PriceFlow Inc.",
      year: 2024,
      category: "Software Development",
      tags: JSON.stringify(["React", "Node.js", "AWS", "PostgreSQL", "Microservices", "UI/UX Design"]),
      coverImageUrl: "/images/proj-sw-1.png",
      imageUrls: JSON.stringify(["/images/proj-sw-1.png"]),
      status: "published",
      featured: true,
      sortOrder: 1,
    },
    {
      title: "ScholarsHub — Global Study Abroad Platform",
      slug: "scholarshub-global",
      description: "Cross-platform mobile app for managing study abroad opportunities — real-time updates, community features, and an intuitive user interface.",
      content: "ScholarsHub needed a centralized platform to connect students with global study opportunities. We designed and developed a React Native application with a clean, modern UI — real-time notifications, social features, and seamless integration with university databases. The app has been downloaded by over 10,000 students.\n\nBuilt with a Node.js backend API and integrated with third-party services for calendar synchronization and messaging.",
      client: "ScholarsHub",
      year: 2024,
      category: "Software Development",
      tags: JSON.stringify(["React Native", "Node.js", "iOS", "Android", "Biometric Auth", "Mobile UI/UX"]),
      coverImageUrl: "/images/proj-sw-2.png",
      imageUrls: JSON.stringify(["/images/proj-sw-2.png"]),
      status: "published",
      featured: true,
      sortOrder: 2,
    },
    {
      title: "HealthNet — Cloud Architecture Migration",
      slug: "healthnet-cloud-migration",
      description: "HIPAA-compliant cloud architecture design and zero-downtime migration for a healthcare network managing 200K patient records.",
      content: "HealthNet's on-premise infrastructure could not scale with their patient volume growth. We designed a HIPAA-compliant AWS architecture, orchestrated the migration of 8TB of sensitive data using the strangler-fig pattern, and implemented automated failover, disaster recovery, and continuous compliance monitoring.\n\nZero data loss. Zero downtime. Ongoing managed infrastructure.",
      client: "HealthNet Group",
      year: 2024,
      category: "Software Development",
      tags: JSON.stringify(["AWS", "HIPAA", "Terraform", "Cloud Migration", "System Architecture"]),
      coverImageUrl: "/images/proj-sw-3.png",
      imageUrls: JSON.stringify(["/images/proj-sw-3.png"]),
      status: "published",
      featured: true,
      sortOrder: 3,
    },
    {
      title: "Maison Noir — Luxury E-Commerce Platform",
      slug: "maison-noir-ecommerce",
      description: "Custom-built luxury fashion e-commerce platform — multi-currency, multi-region, with a bespoke product configurator.",
      content: "Maison Noir required a bespoke e-commerce experience that existing platforms couldn't deliver. We built a fully custom Next.js storefront with a Sanity CMS backend, integrated with Stripe for multi-currency checkout, and a 3D product configurator for their made-to-order line.\n\nPage load time under 1.2s globally. 340% increase in mobile conversion rate.",
      client: "Maison Noir",
      year: 2023,
      category: "Software Development",
      tags: JSON.stringify(["Next.js", "Sanity CMS", "Stripe", "3D Configurator", "E-Commerce", "UI/UX"]),
      coverImageUrl: "/images/proj-sw-4.png",
      imageUrls: JSON.stringify(["/images/proj-sw-4.png"]),
      status: "published",
      featured: false,
      sortOrder: 4,
    },
    {
      title: "CareOS — Patient Management System",
      slug: "careos-patient-management",
      description: "Enterprise patient management and scheduling system with EHR integration, real-time analytics, and GDPR-compliant data architecture.",
      content: "CareOS needed to consolidate four disconnected systems into a single clinical platform used by 400 clinicians across 12 sites. We built a unified patient record system with real-time scheduling, automated appointment reminders, clinical analytics, and a full audit trail.\n\nReduced administrative workload by 60%. 400 clinicians onboarded in under 3 weeks.",
      client: "CareOS Health Systems",
      year: 2023,
      category: "Software Development",
      tags: JSON.stringify(["React", "PostgreSQL", "HL7 FHIR", "Real-time", "Healthcare IT"]),
      coverImageUrl: "/images/proj-sw-5.png",
      imageUrls: JSON.stringify(["/images/proj-sw-5.png"]),
      status: "published",
      featured: false,
      sortOrder: 5,
    },

    // PROMOTION & MEDIA PROJECTS
    {
      title: "Solaris — Product Launch Campaign",
      slug: "solaris-product-launch",
      description: "Full campaign — brand film, social content library of 120+ assets, influencer strategy — launched a new product line to 40K followers in 90 days.",
      content: "Solaris was entering a competitive consumer market with zero social presence and a 90-day runway to their retail launch. We produced the entire campaign: a 3-minute hero brand film, 120+ social assets across Instagram, TikTok and LinkedIn, three influencer partnerships, and managed daily community engagement.\n\nResult: 40K followers, 6.8% engagement rate, 8,000-person waitlist before the shelves were stocked.",
      client: "Solaris Consumer Goods",
      year: 2024,
      category: "Promotion & Media",
      tags: JSON.stringify(["Brand Film", "Social Media", "Content Creation", "Campaign Management", "Photography"]),
      coverImageUrl: "/images/proj-md-1.png",
      imageUrls: JSON.stringify(["/images/proj-md-1.png"]),
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      status: "published",
      featured: true,
      sortOrder: 6,
    },
    {
      title: "Glory Travel — Brand Launch Campaign",
      slug: "glory-travel-brand-launch",
      description: "Complete media and promotion campaign designed to help students discover and apply for international education opportunities.",
      content: "Glory Travel wanted to create an engaging campaign that connects students with life-changing global education opportunities. Many students want to study abroad but find the process confusing and overwhelming. We created a targeted promotional campaign for Glory Travel Agency to reach high school and university students looking for international programs. The project included high-quality social media content, student success video stories, and clear informational graphics that explained visa and university application steps, significantly increasing student inquiries and consultations.",
      client: "Glory Travel",
      year: 2024,
      category: "Promotion & Media",
      tags: JSON.stringify(["Video Production", "Motion Graphics", "Brand Film", "B2B Marketing"]),
      coverImageUrl: "/images/proj-md-2.png",
      imageUrls: JSON.stringify(["/images/proj-md-2.png"]),
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      status: "published",
      featured: true,
      sortOrder: 7,
    },
    {
      title: "Apex Realty — Corporate Brand Identity",
      slug: "apex-realty-brand-identity",
      description: "Full brand video production and social media rollout for a luxury real estate firm — drone cinematography, agent profiles, and property tour series.",
      content: "Apex Realty needed video content that matched the premium properties they sell. We produced a suite of brand assets: an aerial drone showreel of key properties, 12 individual agent profile films, a recurring property tour video series, and a social media content calendar managed for 6 months.\n\nInstagram following grew from 2,100 to 28,000. Property inquiries increased 180% in the first quarter.",
      client: "Apex Realty Group",
      year: 2023,
      category: "Promotion & Media",
      tags: JSON.stringify(["Drone Videography", "Real Estate", "Social Media", "Brand Video", "Photography"]),
      coverImageUrl: "/images/proj-md-3.png",
      imageUrls: JSON.stringify(["/images/proj-md-3.png"]),
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      status: "published",
      featured: false,
      sortOrder: 8,
    },
    {
      title: "Kova — Performance Marketing Campaign",
      slug: "kova-performance-marketing",
      description: "Integrated performance marketing campaign across paid social, organic content, and email — delivered 312% ROI in 60 days.",
      content: "Kova's marketing had plateaued. We audited their entire digital presence, rebuilt their content strategy from the ground up, and ran a 60-day integrated campaign — paid social on Meta and LinkedIn, organic content publishing, email nurture sequences, and a retargeting programme.\n\n312% ROI on ad spend. Cost per acquisition dropped 67%. Monthly revenue increased 40%.",
      client: "Kova Digital",
      year: 2023,
      category: "Promotion & Media",
      tags: JSON.stringify(["Paid Social", "Content Strategy", "Email Marketing", "Performance Marketing", "Analytics"]),
      coverImageUrl: "/images/proj-md-4.png",
      imageUrls: JSON.stringify(["/images/proj-md-4.png"]),
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      status: "published",
      featured: false,
      sortOrder: 9,
    },
  ]);
  console.log("Projects updated (5 software + 4 promotion)");

  console.log("Done.");
  process.exit(0);
}

update().catch(err => { console.error(err); process.exit(1); });
